version: '3'
services:
  build:
    image: docker.io/library/maven:3.9-eclipse-temurin-17
    working_dir: /app
    volumes:
      - .:/app
      - maven-cache:/root/.m2
    command: mvn -B -DskipTests clean package
    profiles:
      - build

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      DEBUG_PORT: '*:8787'
      DEBUG: 'true'
    command: ['start-dev', '--debug', '--import-realm', '--features=client-policies']
    ports:
      - 8080:8080
      - 8443:8443
      - 8787:8787
    volumes:
      - ./src/test/resources/:/opt/keycloak/data/import

volumes:
  maven-cache:
